pub struct Rule {
    pub suffix_in:  &'static str,
    pub suffix_out: &'static str,
    pub reason:     &'static str,
}

macro_rules! rule {
    ($in:expr, $out:expr, $reason:expr) => {
        Rule { suffix_in: $in, suffix_out: $out, reason: $reason }
    };
}

pub static RULES: &[Rule] = &[
    // ── Ichidan (v1): stem + る ────────────────────────────────────────────
    rule!("ない",           "る",    "negative"),
    rule!("なかった",       "る",    "negative past"),
    rule!("ません",         "る",    "polite negative"),
    rule!("ませんでした",   "る",    "polite negative past"),
    rule!("ます",           "る",    "polite"),
    rule!("ました",         "る",    "polite past"),
    rule!("て",             "る",    "te-form"),
    rule!("た",             "る",    "past"),
    rule!("たら",           "る",    "conditional"),
    rule!("たり",           "る",    "alternative"),
    rule!("れば",           "る",    "conditional"),
    rule!("られる",         "る",    "passive/potential"),
    rule!("られない",       "る",    "passive/potential negative"),
    rule!("られた",         "る",    "passive/potential past"),
    rule!("させる",         "る",    "causative"),
    rule!("させない",       "る",    "causative negative"),
    rule!("させた",         "る",    "causative past"),
    rule!("させられる",     "る",    "causative passive"),
    rule!("ろ",             "る",    "imperative"),
    rule!("よ",             "る",    "imperative"),
    rule!("たい",           "る",    "desiderative"),
    rule!("たかった",       "る",    "desiderative past"),
    rule!("たくない",       "る",    "desiderative negative"),
    rule!("ている",         "る",    "progressive"),
    rule!("ていた",         "る",    "progressive past"),
    rule!("ていて",         "る",    "progressive te-form"),
    rule!("ていない",       "る",    "progressive negative"),
    rule!("ていなかった",   "る",    "progressive negative past"),
    rule!("ておく",         "る",    "resultant state"),
    rule!("てしまう",       "る",    "completion"),
    rule!("てしまった",     "る",    "completion past"),
    rule!("てしまって",     "る",    "completion te-form"),
    rule!("てみる",         "る",    "try doing"),
    rule!("てみた",         "る",    "try doing past"),
    rule!("てくる",         "る",    "coming to do"),
    rule!("ていく",         "る",    "going to do"),
    rule!("てある",         "る",    "resultant state"),
    rule!("てほしい",       "る",    "want someone to"),

    // ── Godan: negative (a-stem) ──────────────────────────────────────────
    rule!("かない",         "く",    "negative"),
    rule!("がない",         "ぐ",    "negative"),
    rule!("さない",         "す",    "negative"),
    rule!("たない",         "つ",    "negative"),
    rule!("なない",         "ぬ",    "negative"),
    rule!("ばない",         "ぶ",    "negative"),
    rule!("まない",         "む",    "negative"),
    rule!("らない",         "る",    "negative"),
    rule!("わない",         "う",    "negative"),

    // ── Godan: negative past ──────────────────────────────────────────────
    rule!("かなかった",     "く",    "negative past"),
    rule!("がなかった",     "ぐ",    "negative past"),
    rule!("さなかった",     "す",    "negative past"),
    rule!("たなかった",     "つ",    "negative past"),
    rule!("ななかった",     "ぬ",    "negative past"),
    rule!("ばなかった",     "ぶ",    "negative past"),
    rule!("まなかった",     "む",    "negative past"),
    rule!("らなかった",     "る",    "negative past"),
    rule!("わなかった",     "う",    "negative past"),

    // ── Godan: te-form ────────────────────────────────────────────────────
    rule!("いて",           "く",    "te-form"),
    rule!("いで",           "ぐ",    "te-form"),
    rule!("して",           "す",    "te-form"),
    rule!("って",           "つ",    "te-form"),
    rule!("んで",           "ぬ",    "te-form"),
    rule!("んで",           "ぶ",    "te-form"),
    rule!("んで",           "む",    "te-form"),
    rule!("って",           "る",    "te-form"),
    rule!("って",           "う",    "te-form"),

    // ── Godan: past (ta-form) ─────────────────────────────────────────────
    rule!("いた",           "く",    "past"),
    rule!("いだ",           "ぐ",    "past"),
    rule!("した",           "す",    "past"),
    rule!("った",           "つ",    "past"),
    rule!("んだ",           "ぬ",    "past"),
    rule!("んだ",           "ぶ",    "past"),
    rule!("んだ",           "む",    "past"),
    rule!("った",           "る",    "past"),
    rule!("った",           "う",    "past"),

    // ── Godan: polite (i-stem + ます) ─────────────────────────────────────
    rule!("きます",         "く",    "polite"),
    rule!("ぎます",         "ぐ",    "polite"),
    rule!("します",         "す",    "polite"),
    rule!("ちます",         "つ",    "polite"),
    rule!("にます",         "ぬ",    "polite"),
    rule!("びます",         "ぶ",    "polite"),
    rule!("みます",         "む",    "polite"),
    rule!("ります",         "る",    "polite"),
    rule!("います",         "う",    "polite"),

    // ── Godan: polite negative ────────────────────────────────────────────
    rule!("きません",       "く",    "polite negative"),
    rule!("ぎません",       "ぐ",    "polite negative"),
    rule!("しません",       "す",    "polite negative"),
    rule!("ちません",       "つ",    "polite negative"),
    rule!("にません",       "ぬ",    "polite negative"),
    rule!("びません",       "ぶ",    "polite negative"),
    rule!("みません",       "む",    "polite negative"),
    rule!("りません",       "る",    "polite negative"),
    rule!("いません",       "う",    "polite negative"),

    // ── Godan: polite past ────────────────────────────────────────────────
    rule!("きました",       "く",    "polite past"),
    rule!("ぎました",       "ぐ",    "polite past"),
    rule!("しました",       "す",    "polite past"),
    rule!("ちました",       "つ",    "polite past"),
    rule!("にました",       "ぬ",    "polite past"),
    rule!("びました",       "ぶ",    "polite past"),
    rule!("みました",       "む",    "polite past"),
    rule!("りました",       "る",    "polite past"),
    rule!("いました",       "う",    "polite past"),

    // ── Godan: imperative (e-stem) ────────────────────────────────────────
    rule!("け",             "く",    "imperative"),
    rule!("げ",             "ぐ",    "imperative"),
    rule!("せ",             "す",    "imperative"),
    rule!("ね",             "ぬ",    "imperative"),
    rule!("べ",             "ぶ",    "imperative"),
    rule!("め",             "む",    "imperative"),
    rule!("れ",             "る",    "imperative"),
    rule!("え",             "う",    "imperative"),

    // ── Godan: potential (e-stem + る) ────────────────────────────────────
    rule!("ける",           "く",    "potential"),
    rule!("げる",           "ぐ",    "potential"),
    rule!("せる",           "す",    "potential"),
    rule!("てる",           "つ",    "potential"),
    rule!("ねる",           "ぬ",    "potential"),
    rule!("べる",           "ぶ",    "potential"),
    rule!("める",           "む",    "potential"),
    rule!("れる",           "る",    "potential/passive"),
    rule!("える",           "う",    "potential"),

    // ── Godan: passive (a-stem + れる) ────────────────────────────────────
    rule!("かれる",         "く",    "passive"),
    rule!("がれる",         "ぐ",    "passive"),
    rule!("される",         "す",    "passive"),
    rule!("たれる",         "つ",    "passive"),
    rule!("なれる",         "ぬ",    "passive"),
    rule!("ばれる",         "ぶ",    "passive"),
    rule!("まれる",         "む",    "passive"),
    rule!("われる",         "う",    "passive"),

    // ── Godan: causative (a-stem + せる) ──────────────────────────────────
    rule!("かせる",         "く",    "causative"),
    rule!("がせる",         "ぐ",    "causative"),
    rule!("たせる",         "つ",    "causative"),
    rule!("なせる",         "ぬ",    "causative"),
    rule!("ばせる",         "ぶ",    "causative"),
    rule!("ませる",         "む",    "causative"),
    rule!("らせる",         "る",    "causative"),
    rule!("わせる",         "う",    "causative"),

    // ── Godan: desiderative (i-stem + たい) ───────────────────────────────
    rule!("きたい",         "く",    "desiderative"),
    rule!("ぎたい",         "ぐ",    "desiderative"),
    rule!("したい",         "す",    "desiderative"),
    rule!("ちたい",         "つ",    "desiderative"),
    rule!("にたい",         "ぬ",    "desiderative"),
    rule!("びたい",         "ぶ",    "desiderative"),
    rule!("みたい",         "む",    "desiderative"),
    rule!("りたい",         "る",    "desiderative"),
    rule!("いたい",         "う",    "desiderative"),

    // ── Godan: conditional (e-stem + ば) ──────────────────────────────────
    rule!("けば",           "く",    "conditional"),
    rule!("げば",           "ぐ",    "conditional"),
    rule!("せば",           "す",    "conditional"),
    rule!("てば",           "つ",    "conditional"),
    rule!("ねば",           "ぬ",    "conditional"),
    rule!("べば",           "ぶ",    "conditional"),
    rule!("めば",           "む",    "conditional"),
    rule!("れば",           "る",    "conditional"),
    rule!("えば",           "う",    "conditional"),

    // ── Godan: progressive (te-form + いる) ───────────────────────────────
    rule!("いている",       "く",    "progressive"),
    rule!("いでいる",       "ぐ",    "progressive"),
    rule!("していない",     "す",    "progressive negative"),
    rule!("っている",       "つ",    "progressive"),
    rule!("っている",       "う",    "progressive"),
    rule!("っている",       "る",    "progressive"),
    rule!("んでいる",       "ぬ",    "progressive"),
    rule!("んでいる",       "ぶ",    "progressive"),
    rule!("んでいる",       "む",    "progressive"),
    rule!("いていた",       "く",    "progressive past"),
    rule!("いでいた",       "ぐ",    "progressive past"),
    rule!("っていた",       "つ",    "progressive past"),
    rule!("っていた",       "う",    "progressive past"),
    rule!("っていた",       "る",    "progressive past"),
    rule!("んでいた",       "ぬ",    "progressive past"),
    rule!("んでいた",       "ぶ",    "progressive past"),
    rule!("んでいた",       "む",    "progressive past"),

    // ── I-adjective ───────────────────────────────────────────────────────
    rule!("くない",         "い",    "negative"),
    rule!("くなかった",     "い",    "negative past"),
    rule!("かった",         "い",    "past"),
    rule!("くて",           "い",    "te-form"),
    rule!("ければ",         "い",    "conditional"),
    rule!("く",             "い",    "adverbial"),
    rule!("さ",             "い",    "nominalization"),

    // ── Suru verbs ────────────────────────────────────────────────────────
    // Strip する from a suru-noun stem so chained deinflection reaches the noun.
    // e.g. 流出した → 流出する (した→する) → 流出 (する→"")
    rule!("する",           "",      "suru"),
    rule!("しない",         "する",  "negative"),
    rule!("しなかった",     "する",  "negative past"),
    rule!("せず",           "する",  "negative (literary)"),
    rule!("して",           "する",  "te-form"),
    rule!("した",           "する",  "past"),
    rule!("します",         "する",  "polite"),
    rule!("しました",       "する",  "polite past"),
    rule!("しません",       "する",  "polite negative"),
    rule!("しませんでした", "する",  "polite negative past"),
    rule!("すれば",         "する",  "conditional"),
    rule!("できる",         "する",  "potential"),
    rule!("できない",       "する",  "potential negative"),
    rule!("される",         "する",  "passive"),
    rule!("させる",         "する",  "causative"),
    rule!("させられる",     "する",  "causative passive"),
    rule!("したい",         "する",  "desiderative"),
    rule!("している",       "する",  "progressive"),
    rule!("していた",       "する",  "progressive past"),
    rule!("してしまう",     "する",  "completion"),
    rule!("してしまった",   "する",  "completion past"),

    // ── Kuru (来る) ───────────────────────────────────────────────────────
    rule!("こない",         "くる",  "negative"),
    rule!("こなかった",     "くる",  "negative past"),
    rule!("きて",           "くる",  "te-form"),
    rule!("きた",           "くる",  "past"),
    rule!("きます",         "くる",  "polite"),
    rule!("きました",       "くる",  "polite past"),
    rule!("きません",       "くる",  "polite negative"),
    rule!("くれば",         "くる",  "conditional"),
    rule!("こられる",       "くる",  "potential/passive"),
    rule!("こさせる",       "くる",  "causative"),
    rule!("きている",       "くる",  "progressive"),
    rule!("きていた",       "くる",  "progressive past"),
    rule!("きたい",         "くる",  "desiderative"),
];
